### ISSUE TITLE
本地预览报错

### ISSUE THREAD

**Issue by emyia2001** [hexWars/hexw#1]
git使用npm run dev报错

![{79B5BB47-3856-48c0-854D-B69C63D1629D}](https://github.com/hexWars/hexw/assets/75084293/ccb8b943-2ae8-4b90-bc52-bf70a6baa976)

**Comment by hexWars** [comment]
好的我晚些看一下

**Comment by hexWars** [comment]
ok了

**Comment by hexWars** [comment]
如果对于样式或者功能有什么建议可以和我说

**Comment by emyia2001** [comment]
问题没有解决，这是我的完整报错
[新建文本文档.txt](https://github.com/hexWars/hexw/files/15431589/default.txt)
